# Generated by Django 2.0.3 on 2018-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thomso_serial_key', models.CharField(max_length=40, unique=True, verbose_name='Serial Key/ QR Key')),
                ('name', models.CharField(max_length=128, verbose_name='Team Name/ Participant Name')),
                ('institution', models.CharField(max_length=200, verbose_name="Participant's College")),
                ('event', models.CharField(max_length=120, verbose_name="Participant's Event")),
            ],
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
