# Generated by Django 2.0.3 on 2018-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180709_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='thomso_serial_key',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Serial Key/ QR Key'),
        ),
    ]
